Euro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("HomeApp.urls")),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HomeApp/urls.py
from django.urls import path
from . import views

app_name = "Home"
urlpatterns = [
    path("", views.home_view, name="Login"),
    path("match", views.match_view, name="Match"),
    path("logout", views.logout_view, name="Logout"),
    path("palyers", views.players_table, name="PlayerTable"),
    path("rules", views.rule_view, name="Rules"),
    path("groups", views.group_view, name="Groups"),
    path("history", views.history_view, name="History"),
    path("today", views.today_forcast, name="TodayForcast")
]

HomeApp/models.py
from datetime import timezone

from django.db import models
from django.contrib.auth.models import User


class Score(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="scores", verbose_name="کاربر")
    score = models.PositiveIntegerField(default=0, verbose_name="امتیاز")

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

    class Meta:
        verbose_name = "امتیاز"
        verbose_name_plural = "امتیازات"


class MatchDay(models.Model):
    title = models.CharField(max_length=150, verbose_name="عنوان")
    text = models.TextField(verbose_name="نوشته")
    group = models.BooleanField(default=False, verbose_name="مرحله گروهی")
    knockout = models.BooleanField(default=False, verbose_name="مرحله حذفی")
    semiFinal = models.BooleanField(default=False, verbose_name="مرحله نیمه نهایی")
    final = models.BooleanField(default=False, verbose_name="مرحله فینال")
    date = models.DateTimeField(auto_now_add=True)
    first_match_start = models.TimeField(verbose_name="زمان شروع اولین مسابقه")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "مسابقه"
        verbose_name_plural = "مسابقات"


class Match(models.Model):
    matchday = models.ForeignKey(MatchDay, on_delete=models.CASCADE, related_name="matches", verbose_name="روز بازی")
    home_name = models.CharField(max_length=100, default=" ")
    away_name = models.CharField(max_length=100, default=" ")
    home = models.CharField(max_length=2, blank=True, null=True, verbose_name="تعداد گل میزبان")
    home_img = models.ImageField(upload_to="images", blank=True, null=True, verbose_name="تصویر میزبان")
    away = models.CharField(max_length=2, blank=True, null=True, verbose_name="تعداد گل میهمان")
    away_img = models.ImageField(upload_to="images", blank=True, null=True, verbose_name="تصویر میهمان")

    def __str__(self):
        return f"{self.home_name} vs {self.away_name}"

    class Meta:
        verbose_name = "بازی"
        verbose_name_plural = "بازیها"


class UserForcast(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="forcast", verbose_name="کاربر")
    matchday = models.ForeignKey(MatchDay, on_delete=models.CASCADE, related_name="forcast", verbose_name="روز بازی")
    match = models.ForeignKey(Match, on_delete=models.CASCADE, related_name="forcast", verbose_name="بازی")
    home_name = models.CharField(max_length=100, default=" ")
    away_name = models.CharField(max_length=100, default=" ")
    home = models.CharField(max_length=2, verbose_name="تعداد گل میزبان")
    home_img = models.ImageField(upload_to="images", blank=True, null=True, verbose_name="تصویر میزبان")
    away = models.CharField(max_length=2, verbose_name="تعداد گل میهمان")
    away_img = models.ImageField(upload_to="images", blank=True, null=True, verbose_name="تصویر میهمان")

    def __str__(self):
        return f"{self.user}//{self.home_name}vs {self.away_name}//{self.home} - {self.away}"

    class Meta:
        verbose_name = "پیش بینی"
        verbose_name_plural = "پیش بینی ها"


class Rule(models.Model):
    title = models.CharField(max_length=200, verbose_name="عنوان")
    body = models.TextField(verbose_name="متن قوانین")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "مطلب"
        verbose_name_plural = "قوانین"


class UserForcastHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="history", verbose_name="کاربر")
    matchday = models.ForeignKey(MatchDay, on_delete=models.CASCADE, related_name="history", verbose_name="روز بازی")
    match = models.ForeignKey(Match, on_delete=models.CASCADE, related_name="history", verbose_name="بازی")
    home_name = models.CharField(max_length=100, default=" ")
    away_name = models.CharField(max_length=100, default=" ")
    home = models.CharField(max_length=2, verbose_name="تعداد گل میزبان")
    home_img = models.ImageField(upload_to="images", blank=True, null=True, verbose_name="تصویر میزبان")
    away = models.CharField(max_length=2, verbose_name="تعداد گل میهمان")
    away_img = models.ImageField(upload_to="images", blank=True, null=True, verbose_name="تصویر میهمان")

    def __str__(self):
        return f"{self.user}//{self.home_name}vs {self.away_name}//{self.home} -{self.away}"

    class Meta:
        verbose_name = "تاربخچه پیش بینی"
        verbose_name_plural = " تاربخچه پیش بینی ها"

HomeApp/views.py
import datetime

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.utils import timezone
from django.contrib import messages

from .models import Match, MatchDay, Score, User, UserForcast, Rule, UserForcastHistory
from datetime import date, time


def home_view(request):
    time = datetime.datetime.now()
    if request.user.is_authenticated:
        return redirect("Home:Match")
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "با موفقیت وارد شدید")
            return redirect("Home:Match")
        else:
            messages.error(request, "ایمیل یا پسورد اشتباه است")
    return render(request, "HomeApp/login.html", context={"time": time})


def match_view(request):
    today = date.today()
    two_am = time(hour=2)
    matches = Match.objects.filter(matchday__date__day=today.day)
    if matches:
        user_forecasts_exist = UserForcast.objects.filter(user=request.user,
                                                          matchday__date__day=today.day).exists()
        matching_day = MatchDay.objects.filter(date__day=today.day).first()
        if matching_day:
            first_match_start = matching_day.first_match_start

        submission_time = timezone.now().time()
        if request.method == "POST" and not user_forecasts_exist:
            for match in matches:
                matchday = match.matchday
                user = request.user
                home_name = match.home_name
                away_name = match.away_name
                home = request.POST.get(f'home-{match.id}')
                away = request.POST.get(f'away-{match.id}')
                home_img = match.home_img
                away_img = match.away_img
                UserForcast.objects.create(user=user, home_name=home_name, away_name=away_name, matchday=matchday,
                                           home=home,
                                           away=away, home_img=home_img, away_img=away_img, match=match)
                messages.success(request, "پیش بینی شما ثبت شد")

            return redirect("Home:Logout")
        return render(request, "HomeApp/Match.html",
                      context={"matches": matches, "user_forecasts_exist": user_forecasts_exist,
                               "first_match_start": first_match_start, "two_am": two_am,
                               "submission_time": submission_time})
    else:
        return render(request, "HomeApp/Nomatch.html")


def logout_view(request):
    logout(request)
    return redirect("/")


def players_table(request):
    users = User.objects.filter(forcast__isnull=False).distinct()
    scores = Score.objects.all().order_by("-score")
    for user in users:
        forcasts = UserForcast.objects.filter(user=user)
        score, created = Score.objects.get_or_create(user=user, defaults={'score': 0})
        for forcast in forcasts:
            if forcast.match.home is not None and forcast.match.away is not None:
                final_home = int(forcast.match.home)
                final_away = int(forcast.match.away)
                user_home = int(forcast.home)
                user_away = int(forcast.away)
                final_score = f"{forcast.match.home}{forcast.match.away}"
                final_score = int(final_score)
                user_score = f"{forcast.home}{forcast.away}"
                user_score = int(user_score)
                # checking for Group Stage

                if forcast.matchday.group:
                    if final_score == user_score:
                        score.score += 10
                        score.save()
                    elif (abs(final_home - final_away) == abs(user_home - user_away)) and (
                            user_home != final_home) and (
                            user_away != final_away) and (
                            (user_home > user_away and final_home > final_away) or (
                            user_away > user_home and final_away > final_home)):
                        score.score += 7
                        score.save()
                    elif (abs(final_home - final_away) != abs(user_home - user_away)) and (
                            (user_home > user_away and final_home > final_away) or (
                            user_away > user_home and final_away > final_home)):
                        score.score += 5
                        score.save()
                    elif (user_away == user_home) and (final_away == final_home) and (user_away != final_away):
                        score.score += 7
                        score.save()
                    else:
                        score.score += 2
                        score.save()
                #         Checking For Knockout Stage

                elif forcast.matchday.knockout:
                    if final_score == user_score:
                        score.score += (10 * 3)
                        score.save()
                    elif (abs(final_home - final_away) == abs(user_home - user_away)) and (
                            user_home != final_home) and (
                            user_away != final_away) and (
                            (user_home > user_away and final_home > final_away) or (
                            user_away > user_home and final_away > final_home)):
                        score.score += (7 * 3)
                    elif (abs(final_home - final_away) != abs(user_home - user_away)) and (
                            (user_home > user_away and final_home > final_away) or (
                            user_away > user_home and final_away > final_home)):
                        score.score += (5 * 3)
                        score.save()
                    elif (user_away == user_home) and (final_away == final_home) and (user_away != final_away):
                        score.score += (7 * 3)
                        score.save()
                    else:
                        score.score += (2 * 3)
                        score.save()
                #         Checking for Semi-Final

                elif forcast.matchday.semiFinal:
                    if final_score == user_score:
                        score.score += (10 * 4)
                        score.save()
                    elif (abs(final_home - final_away) == abs(user_home - user_away)) and (
                            user_home != final_home) and (
                            user_away != final_away) and (
                            (user_home > user_away and final_home > final_away) or (
                            user_away > user_home and final_away > final_home)):
                        score.score += (7 * 4)
                    elif (abs(final_home - final_away) != abs(user_home - user_away)) and (
                            (user_home > user_away and final_home > final_away) or (
                            user_away > user_home and final_away > final_home)):
                        score.score += (5 * 4)
                        score.save()
                    elif (user_away == user_home) and (final_away == final_home) and (user_away != final_away):
                        score.score += (7 * 4)
                        score.save()
                    else:
                        score.score += (2 * 4)
                        score.save()
                #     Checking For Final Stage

                elif forcast.matchday.final:
                    if final_score == user_score:
                        score.score += (10 * 6)
                        score.save()
                    elif (abs(final_home - final_away) == abs(user_home - user_away)) and (
                            user_home != final_home) and (
                            user_away != final_away) and (
                            (user_home > user_away and final_home > final_away) or (
                            user_away > user_home and final_away > final_home)):
                        score.score += (7 * 6)
                        score.save()
                    elif (abs(final_home - final_away) != abs(user_home - user_away)) and (
                            (user_home > user_away and final_home > final_away) or (
                            user_away > user_home and final_away > final_home)):
                        score.score += (5 * 6)
                        score.save()
                    elif (user_away == user_home) and (final_away == final_home) and (user_away != final_away):
                        score.score += (7 * 6)
                        score.save()
                    else:
                        score.score += (2 * 6)
                        score.save()
                else:
                    print("ridi")
                UserForcastHistory.objects.create(user=forcast.user, away_name=forcast.away_name,
                                                  home_name=forcast.home_name, home=forcast.home, away=forcast.away,
                                                  home_img=forcast.home_img, away_img=forcast.away_img,
                                                  matchday=forcast.matchday, match=forcast.match)
                forcast.delete()
    return render(request, "HomeApp/scores.html", context={"users": users, "scores": scores})


def rule_view(request):
    rule = Rule.objects.all().last()
    return render(request, "HomeApp/rules.html", context={"rule": rule})


def group_view(request):
    return render(request, "HomeApp/groups.html")


def history_view(request):
    history = UserForcastHistory.objects.filter(user=request.user)
    return render(request, "HomeApp/history.html", context={"items": history})


def today_forcast(request):
    today = date.today()

HomeApp/templates/HomeApp/Match.html
{% extends "base.html" %}
{% load static %}
{% block title %}صفه پیش بینی{% endblock %}
{% block content %}
    <!-- Matches -->
    <h1>{{ submission_time }}</h1>
    <div class="container mt-5 mb-5">
    {% for msg in messages %}
     <div class="alert alert-success mb-5" role="alert" id="alert">
                {{ msg }}
            </div>
    {% endfor %}
        <div class="row d-flex justify-content-center mt-5">


            <div class="col-lg-12 col-md-6 col-sm-12 d-flex justify-content-center align-items-center mt-5 ">
                {% if user_forecasts_exist %}
                    <div class="alert alert-warning">
                        <strong>Warning!</strong> شما یکبار امروز پیش بینی کرده اید!
                    </div>
                {% else %}

                    {% if submission_time > first_match_start or submission_time < two_am %}
                        <div class="alert alert-warning">
                            <strong>Warning!</strong> شما نمی توانید در ساعات پس از مسابقه اول تا 2 صبح پیش بینی
                            کنید
                        </div>
                    {% else %}

                        <form method="post"  id="myForm">
                            {% csrf_token %}
                            {% for match in matches %}
                                <div class="d-flex justify-content-center align-items-center mb-5">
                                    <div class="me-5"><img src="{{ match.home_img.url }}" alt="">
                                        <p>{{ match.home_name }}</p>
                                        <input type="text" class="form-control" name="home-{{ match.id }}">
                                    </div>
                                    <div class="ms-5"><img src="{{ match.away_img.url }}" alt="">
                                        <p>{{ match.away_name }}</p>
                                        <input type="text" class="form-control" name="away-{{ match.id }}">
                                    </div>
                                </div>
                                <hr class="mt-5 match">

                            {% endfor %}
                            <button type="submit " id="submitButton" class="btn btn-primary mt-5">ارسال</button>
                        </form>
                        </div>
                    {% endif %}
                {% endif %}

        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 d-flex justify-content-center align-items-center mt-5 me">
            <div>
                <a class="btn btn-primary mt-5" href="{% url "Home:History" %}">سابقه پیش بینی های شما</a>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

HomeApp/templates/HomeApp/Nomatch.html
{% extends "base.html" %}
{% load static %}
{% block title %}تاریخچه پیش بینی ها{% endblock %}
{% block content %}
    <!-- Matches -->
    <div class="container mt-5 mb-5">
        <div class="row d-flex justify-content-center mt-5">

            <div class="col-lg-12 col-md-12 col-sm-12 d-flex justify-content-center align-items-center mt-5 me">
                 <div class="alert alert-warning">
                        <strong>Warning!</strong> مسابقه ای برای نمایش نیست
                    </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 d-flex justify-content-center align-items-center mt-5 me">
                 <div>
                        <a class="btn btn-primary mt-5" href="{% url "Home:History" %}">سابقه پیش بینی های شما</a>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}

HomeApp/templates/HomeApp/groups.html
{% extends "base.html" %}
{% load static %}
{% block title %}گروه بندی جام ملتهای اروپا{% endblock %}
{% block content %}
    <!-- groups -->

    <div class="container-fluid">
        <section class="content-info mt-5 ms-5 mb-5">
            <div class="container mt-5 ms-5 group-container">
                <div class="groups-list page-group mt-5 ms-5">
                    <div class="row ms-5">
                        <div class="col-lg-3 col-md-6 ms-5 group-table ">
                            <div class="group-title mb-3">
                                <h5 class="mb-5 d-flex justify-content-center align-items-center"><a href="#">گروه a</a>
                                </h5></div>
                            <div class="item-group">
                                <ul>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/ger.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/scot.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/hungary.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/icons8-switzerland-70.png' %}" alt=""></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6  ms-5 group-table">
                            <div class="group-title mb-3">
                                <h5 class="mb-5 d-flex justify-content-center align-items-center"><a href="#">گروه b</a>
                                </h5></div>
                            <div class="item-group">
                                <ul>
                                    <li class="d-flex justify-content-center align-items-center mb-3">
                                        <a href="#">
                                            <img src="{% static 'logos/esp.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/cro.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/italy.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/albania.png' %}" alt=""></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 ms-5 group-table">
                            <div class=" group-title">
                                <h5 class="mb-5 d-flex justify-content-center align-items-center"><a href="#">گروه c</a>
                                </h5></div>
                            <div class="item-group">
                                <ul>
                                    <li class="d-flex justify-content-center align-items-center ">
                                        <a href="#">
                                            <img src="{% static 'logos/slovenia.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center mb-3 ">
                                        <a href="#">
                                            <img src="{% static 'logos/den.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center mb-3">
                                        <a href="#">
                                            <img src="{% static 'logos/srb.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center ">
                                        <a href="#">
                                            <img src="{% static 'logos/eng.png' %}" alt=""></a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                    </div>
                    <div class="row ms-5 mt-3">
                        <div class="col-lg-3 col-md-6 ms-5 group-table">
                            <div class="group-title mb-3">
                                <h5 class="mb-5 d-flex justify-content-center align-items-center "><a href="#">گروه
                                    d</a></h5></div>
                            <div class="item-group">
                                <ul>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/pol.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/netherlands.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/austria.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">

                                        <a href="#">
                                            <img src="{% static 'logos/fra.png' %}" alt=""></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 ms-5 group-table">
                            <div class="group-title mb-3">
                                <h5 class="mb-5 d-flex justify-content-center align-items-center "><a href="#">گروه
                                    e</a></h5></div>
                            <div class="item-group">
                                <ul>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/bel.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/slovakia.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/romania.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/urkraine.png' %}" alt=""></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 ms-5 group-table">
                            <div class="group-title ">
                                <h5 class="mb-5 d-flex justify-content-center align-items-center  "><a href="#">گروه
                                    f</a></h5></div>
                            <div class="item-group">
                                <ul>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/turkey.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/georgia.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/por.png' %}" alt=""></a>
                                    </li>
                                    <hr>
                                    <li class="d-flex justify-content-center align-items-center">
                                        <a href="#">
                                            <img src="{% static 'logos/czechia.png' %}" alt=""></a>
                                    </li>
                                </ul>

                            </div>
                        </div>
                    </div>

        </section>
    </div>
{% endblock %}

HomeApp/templates/HomeApp/history.html
{% extends "base.html" %}
{% load static %}
{% block title %}تاریخچه پیش بینی ها{% endblock %}
{% block content %}
    <!-- Matches -->
    <div class="container mt-5 mb-5">
        <div class="row d-flex justify-content-center mt-5">

            {% for item in items %}
                <div class="col-lg-12 col-md-12 col-sm-12 d-flex justify-content-center align-items-center mt-5 me">
                    <div class="me-5 col-lg-4"><img src="{{ item.home_img.url }}" alt="">
                        <p>{{ item.home_name }} <span>{{ item.home }}</span></p></div>
                    <div class=" col-lg-4"><img src="{{ item.away_img.url }}" alt="">
                        <p>{{ item.away_name }} <span>{{ item.away }}</span></p></div>
                </div>

                <hr class="mt-5 match">
            {% endfor %}
        </div>
    </div>
{% endblock %}

HomeApp/templates/HomeApp/rules.html
{% extends "base.html" %}
{% load static %}
{% block title %}قوانین و مقررات{% endblock %}
{% block content %}
    <div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-8">
            <h2>{{ rule.title }}</h2>
            <hr>
            <p>{{ rule.body|safe }}</p>
        </div>
    </div>
  </div>
{% endblock %}