Euro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("HomeApp.urls")),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HomeApp/urls.py
from django.urls import path
from . import views

app_name = "Home"
urlpatterns = [
    path("", views.home_view, name="Login"),
    path("match", views.match_view, name="Match"),
    path("logout", views.logout_view, name="Logout"),
    path("palyers", views.players_table, name="PlayerTable"),
    path("rules", views.rule_view, name="Rules"),
    path("groups", views.group_view, name="Groups"),
    path("history", views.history_view, name="History"),
    path("today", views.today_forcast, name="TodayForcast")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css"
          integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<a href="tel:09128362806" class="contact"><img src="{% static 'logos/whatsapp.gif' %}" alt="contact"></a>
<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="{% static 'img/euro-logo.png' %}" alt="" width="90" height="90"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse ms-5" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item ms-5">
                    <a class="nav-link {% if request.resolver_match.url_name == "Login" or request.resolver_match.url_name == "Match" %}active" {% endif %}
                       aria-current="page" href="{% url 'Home:Login' %}"><i class="bi bi-house"></i>خانه </a>
                </li>
                <li class="nav-item ms-5">
                    <a class="nav-link {% if request.resolver_match.url_name == "Rules" %} active {% endif %}"
                       href="{% url 'Home:Rules' %}"> <i class="bi bi-file-earmark-ruled"></i> قوانین و نحوه امتیازات
                    </a>
                </li>
                <li class="nav-item ms-5">
                    <a class="nav-link {% if request.resolver_match.url_name == "PlayerTable" %} active {% endif %}"
                       href="{% url 'Home:PlayerTable' %}"><i class="bi bi-table"></i> جدول شرکت کنندگان </a>
                </li>
                <li class="nav-item ms-5">
                    <a class="nav-link {% if request.resolver_match.url_name == "Groups" %} active {% endif %}"
                       href="{% url 'Home:Groups' %}"> <i class="bi bi-check"></i> گروه بندی </a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item ms-5">
                        <a class="nav-link" href="{% url "Home:TodayForcast" %}">پیش بینی های امروز</a>
                    </li>
                    <li class="nav-item ms-5">
                        <a class="nav-link" href="{% url "Home:Logout" %}">خروج </a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>

{% block content %}
{% endblock %}
<!-- footer -->

<div class="container-fluid bg-light ">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{% url "Home:Login" %}" class="nav-link px-2 ">خانه</a></li>
            <li class="nav-item"><a href="{% url 'Home:Rules' %}" class="nav-link px-2 ">قوانین و نحوه امتیازات</a></li>
            <li class="nav-item"><a href="{% url 'Home:PlayerTable' %}" class="nav-link px-2 ">جدول شرکت کنندگان</a>
            </li>
            <li class="nav-item"><a href="{% url "Home:Groups" %}" class="nav-link px-2 ">گروه بندی</a></li>
        </ul>
        <p class="text-center">© 2024 FC Forsite, Inc</p>
    </footer>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const alerts = document.querySelectorAll("#alert");
        alerts.forEach(alert => {
            setTimeout(function () {
                alert.classList.add("d-none"); // Add class to hide the div
            }, 3000); // Wait for 3 seconds (3000 milliseconds)
        });
    });
    const submitButton = document.getElementById('submitButton');
    const myForm = document.getElementById('myForm');

    submitButton.addEventListener('click', function () {
        if (!myForm.hasAttribute('submitted')) {
            myForm.submit();
            myForm.setAttribute('submitted', 'true'); // Mark as submitted
            submitButton.disabled = true; // Disable button (optional)
        } else {
            alert('Form already submitted!'); // Optional alert for repeated clicks
        }
    });
</script>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</html>